### PR TITLE
starter code loading from firebase

### PR DESCRIPTION
**Pull request by almeidaalajoel**
@toto4tots @zgalant 

demo:
https://www.loom.com/share/34fc8e60b6fd4157b67a3774de3121ae
code:
https://www.loom.com/share/cfa98b866d3e4ea0951ab9ff3cf6d43a

branches from URL refactor
copilot:all

### CODE REVIEW

**Comment by toto4tots** [comment]
@almeidaalajoel 
How do you get a project with a valid item id locally?

**Comment by zgalant** [comment]
@toto4tots @almeidaalajoel you may need to make a section on the live site to make the urls and set up the starter code from there

**Comment by almeidaalajoel** [comment]
@toto4tots I've just been setting the URLparams manually when navigating to a project ie localhost:8080/editions/free/src/home.html?item_id=x

**Comment by toto4tots** [comment]
Just talked with Joel - 
We have a bit of a quirk where if we go to the editor directly, it’ll error so instead we want to go to http://localhost:8080/editions/free/src/home.html?item_id=1000 which will redirect us to the editor
edit: no need for a valid item id for this PR

**Comment by toto4tots** [comment]
Just tested and working as expected. I think we can merge this @almeidaalajoel

**Pull request merged**
