### PR TITLE
fix scripts, add alphanum characters as sprites [100%]

### PR DESCRIPTION
**Pull request by almeidaalajoel**
@toto4tots 

PR fixes some scripts left by saar for fixing SVGs. Adds a new script for resizing SVGs. 

also adds alphanumeric characters as sprites.

### CODE REVIEW

**Comment by dkrame11** [comment]
@toto4tots can you review this and then we should merge this

**Comment by toto4tots** [comment]
Planning to pair w Joel on Monday about it. Do we want to get this merged today? @dkrame11

**Comment by dkrame11** [comment]
no monday is fine

**Comment by toto4tots** [comment]
Paired w Joel on this, talked about some of the limitations but this is working for me 
Just one note that right now, we're not really able to customize these characters.
Namely, we can't change the color of the 'a'
image

edit: 
looks like the changes do show up in the edit gallery(??)
image


I think this is okay for now but something to note for elementary team

**Review by toto4tots — APPROVED** [review]

**Pull request merged**
