### PR TITLE
Optimize saves [100%]

### PR DESCRIPTION
**Pull request by Bloblblobl**
@zgalant @toto4tots 

I ran into an issue this morning where my ScratchJr program wasn't saving properly - at first I thought it was related to the fullscreen mode but I think it's actually related to race conditions with the way we're currently saving ScratchJr projects (fullscreen mode is now live since its unrelated).

We set up the integration to save the DB and make a save request to CodeHS after a SQL statement is executed on the DB. Because of this, we were sometimes saving multiple times in quick successions because multiple statements were being executed on save. This changes the way saving works (in a kind of hacky way) to account for that - instead of saving immediately, we start a 1s timeout that will save once its finished, and then clear and reset the timeout whenever save is called again within that timespan. There are probably better ways to approach this problem, but I think we would need to untangle/dig into more of the ScratchJr spaghetti code, so I don't think its worth it and I think this should be good enough (we can also try out lowering the timeout from 1s, maybe 0.1s is good enough). 

In addition, the way we were checking whether any changes were made wasn't good enough, so we were continuously sending save requests even if no changes were being made - I made a fix to that too, so now we should only make 1 save request per change at most.

There is still one weird issue where we're sending a save request on page load which I'm not sure about, but I don't know if that's worth to dig into now.

Loom explanation:
https://www.loom.com/share/53dbb3947e8e4bde8e309b51ef3c1ca1 

Steps to test:
[See the notion page for set up](https://www.notion.so/codehs/Scratch-ScratchJr-fae5d776041d479c914dc8fddc80517b?pvs=4#272a94cc65e34ca799636f263e8d5ebf)
Open the network tab on a ScratchJr program
Filter on for Fetch/XHR requests and for the text "save":
image
Verify that a save request is only sent once per change, either on the autosave or after manually saving, and that the autosaver doesn't keep sending requests if nothing has changed

### CODE REVIEW

**Comment by zgalant** [comment]
good stuff- can you make a quick loom walking through the code?

**Comment by toto4tots** [comment]
Reviewed code w Saar during pair session.
When I make changes to the project I get a toastr error from `ajax_scratchjr_save` which looks like it's due to `request.FILES` being empty (`django.utils.datastructures.MultiValueDictKeyError`)

Screen Shot 2023-11-07 at 1 40 19 PM

**Comment by Bloblblobl** [comment]
@zgalant made a walkthrough while Kyuri and I were pairing here: https://www.loom.com/share/7cca37f320fb4d4bad7f41c2be09495e

@toto4tots I think that might be because of outdated codehs-side JS? you might've needed to refresh the cache. There shouldn't have been anything changed in this PR to cause that issue. I'll test this out more though to confirm, I know youre OOO for the rest of the week

**Comment by toto4tots** [comment]
@Bloblblobl Ah I think you're right. Just retested + cleared my cache and no longer getting that error. I think we can merge

**Pull request merged**
